### Retrieve all contacts
GET http://localhost:3000/contacts
Accept: application/json

### Retrieve a single contact by ID
GET http://localhost:3000/contacts/67cc8ba11959b71238777f31
Accept: application/json

### Create a new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Beatriz",
    "lastName": "Miranda",
    "email": "beatriz.miranda@gmail.com",
    "favoriteColor": "blue",
    "birthday": "2001-04-26"
}

### Update a contact by ID
PUT http://localhost:3000/contacts/67cc8bee1959b71238777f32
Content-Type: application/json

{
    "firstName": "Ilmar",
    "lastName": "Miranda",
    "email": "ilmar.miranda@gmail.com",
    "favoriteColor": "green",
    "birthday": "1969-02-23"
}

### Delete a contact by ID
DELETE http://localhost:3000/contacts/67cb99cf77fd45346ffd96f4
